version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: matrx-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  matrx-renderer:
    build: .
    container_name: matrx-renderer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - AMQP_EXCHANGE=matrx
      - AMQP_QUEUE=render_requests
      - AMQP_ROUTING_KEY=render
      - AMQP_RESULT_QUEUE=render_results
      - PIXLET_APPS_PATH=/opt/apps
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: pgrep matrx-renderer > /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
