name: Docker Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    uses: acvigue/.github/.github/workflows/docker_build.yml@main
  deploy:
    needs: build
    uses: acvigue/.github/.github/workflows/argocd_redeploy.yml@main
    with:
      argocd_repo: "koiosdigital/kubernetes"
      deployment_file: "base/device-api/matrx-renderer-deployment.yaml"
    secrets: inherit
