name: Docker Build
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1,3,5"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/${{ github.repository }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
